import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <p className="text-blue-500">这里是全局布局</p>
        {children}
      </body>
    </html>
  )
}
