import './globals.css'

import Header from './components/Header'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh-CN">
      <body className="bg-custom-background lg:px-8">
        <Header />
        {children}
      </body>
    </html>
  )
}
