name: Vercel CI/CD when markdown update

on:
  repository_dispatch:
    types: [markdown-update]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Deployment
    steps:
      - name: Trigger Vercel Deployment
        run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}
